= Collections good practices

Note: Unreviewed work. Please contribute to the discussion in the Automation Red Hat COP

=== Collection Structure should be at the type or landscape level
[%collapsible]
====
Explanations:: Collections should be comprised of roles collected either at the type or landscape level. See <<structures/README.adoc#_define_which_structure_to_use_for_which_purpose,The Structures Definition>>

Rationale:: Gathering and publishing collections, rather than individual roles, allows for easier distribution and particularly becomes more important when we discuss Execution Environments.

====

=== Create implicit collection variables and reference them in your roles' defaults variables
[%collapsible]
====
Explanations:: Often, variables will want to be defined on a collection level, but this can cause issues with roles being able to be reused.
By defining collection wide variables and referencing them in roles' defaults variables, this can be made clear and roles can remain reusable.
Collection variables are nowhere defined explicitly and are to be documented in the collection's documentation.

Rationale:: Variables that are shared across collections can cause collisions when roles are reused outside of the original collection.

Examples::
For a collection "mycollection", two roles exist. "alpha" and "beta".
+
.Alpha defaults/main.yml
[source,yaml]
----
# specific role variables
alpha_job_name: 'some text'
# collection wide variables
alpha_controller_username: "{{ mycollection_controller_username }}"
alpha_no_log: "{{ mycollection_no_log | default('true') }}"
----
+
.Beta defaults/main.yml
[source,yaml]
----
# specific role variables
beta_job_name: 'some other text'
# collection wide variables
beta_controller_username: "{{ mycollection_controller_username }}"
beta_no_log: "{{ mycollection_no_log | default('false') }}"
----
====

