- name: Wrap long Jinja expressions
  ansible.builtin.set_fact:
    wrapped_value: "{{ a_very.long_variable.name |
      somefilter('with', 'many', 'arguments') |
      another_filter | list }}"
  when: a_very.long_variable.name |
    somefilter('with', 'many', 'arguments') |
    another_filter | list

- name: Wrap when first line is already too long
  ansible.builtin.set_fact:
    very_indented_value: "{{
      a_very.long_variable.name |
      somefilter('with', 'many', 'arguments') |
      another_filter | list }}"
  when: \
    a_very.long_variable.name |
    somefilter('with', 'many', 'arguments') |
    another_filter | list | length > 0

- name: Set some test variables
  ansible.builtin.set_fact:
    my_very_long_variable_1: "{{ __pre_digest | filter1 }}"
    my_very_long_variable_2: "{{ __pre_digest | filter2 }}"
  vars:
    __pre_digest: "{{ a_very.long_variable.name | some_filter }}"

- name: Use a very long URL
  ansible.builtin.uri:
    url: "https://{{ my_very_long_value_for_hostname }}:\
      {{ my_very_long_value_for_port }}\
      {{ my_very_long_value_for_uri }}?\
      {{ my_very_long_value_for_query }}"
