- name: Set vars file list
  ansible.builtin.set_fact:
    __rolename_vars_file_list:
      - "{{ ansible_facts['os_family'] }}.yml"
      - "{{ ansible_facts['distribution'] }}.yml"
      - >-
        {{ ansible_facts['distribution'] }}_{{
        ansible_facts['distribution_major_version'] }}.yml
      - >-
        {{ ansible_facts['distribution'] }}_{{
        ansible_facts['distribution_version'] }}.yml

- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __rolename_vars_file }}"
  loop: "{{ __rolename_vars_file_list | unique | list }}"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file
