---
- name: Debug verbosity examples
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Don't make messages always display
      ansible.builtin.debug:
        msg: "This message will clutter your log in production"

    - name: This message will only appear when verbosity is 2 or more
      ansible.builtin.debug:
        msg: "Some more debug information if needed"
        verbosity: 2
