name: test document generation

on:
  pull_request:

jobs:
  test-build-docs:

    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install requirements
      run: sudo dnf install -y git graphviz make plantuml rubygem-asciidoctor rubygem-asciidoctor-pdf rubygem-rouge

    - name: Move to the correct folder
      run: cd $GITHUB_WORKSPACE

    - name: Render HTML
      run: make release
